services:
  db:
    image: mysql
    container_name: database
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db

  web:
    image: 'bitnami/symfony:1'
    ports:
    - 8000:80
    links:
      - app













